"""empty message

Revision ID: 77f962266416
Revises: 7bb8b8e0b9f2
Create Date: 2023-03-20 18:49:54.399001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f962266416'
down_revision = '7bb8b8e0b9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.String(length=300), nullable=False))
        batch_op.drop_constraint('auctions_project_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('auctions_project_fkey', 'projects', ['project'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
