"""add auction and project tables

Revision ID: 883920a66dc3
Revises: 77b68053207a
Create Date: 2023-03-16 21:41:54.037357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883920a66dc3'
down_revision = '77b68053207a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('claim_number', sa.Integer(), nullable=False),
    sa.Column('claim_object', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('project', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['project'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auctions')
    # ### end Alembic commands ###
