"""init db

Revision ID: c1ac1cdc4273
Revises: 
Create Date: 2023-03-24 01:20:53.449017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ac1cdc4273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=80), server_default='', nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('role', sa.ARRAY(sa.String(length=80)), nullable=False),
    sa.Column('_password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auctions',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('claim_number', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('claim_object', sa.Text(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_number'),
    sa.UniqueConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('projects_indetifier',
    sa.Column('user_id', sa.String(length=300), nullable=True),
    sa.Column('project_id', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects_indetifier')
    op.drop_table('logs')
    op.drop_table('auctions')
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
